In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("./data/id9o0mbu0rvqqbuf.csv")

In [9]:
df.head()

,DATE,TIME_M,EX,BID,BIDSIZ,ASK,ASKSIZ,QU_COND,QU_SEQNUM,NATBBO_IND,QU_CANCEL,QU_SOURCE,SYM_ROOT,SYM_SUFFIX
0,2023-05-10,3:59:00.005197350,K,0.00,0,0.00,0,L,1090,1,NaN,N,AAPL,NaN
1,2023-05-10,3:59:00.095617932,Z,0.00,0,0.00,0,L,2024,1,NaN,N,AAPL,NaN
2,2023-05-10,4:00:00.003953823,Q,171.23,4,0.00,0,R,3892,2,NaN,N,AAPL,NaN
3,2023-05-10,4:00:00.003974778,Q,171.23,4,171.44,4,R,3893,4,NaN,N,AAPL,NaN
4,2023-05-10,4:00:00.005169850,K,171.02,10,0.00,0,Y,3953,0,NaN,N,AAPL,NaN

In [18]:
df[df.where((df["ASK"] == 0) & (df["ASKSIZ"] > 0))].isnull().sum()

DATE          11590088
TIME_M        11590088
EX            11590088
BID           11590088
BIDSIZ        11590088
ASK           11590088
ASKSIZ        11590088
QU_COND       11590088
QU_SEQNUM     11590088
NATBBO_IND    11590088
QU_CANCEL     11590088
QU_SOURCE     11590088
SYM_ROOT      11590088
SYM_SUFFIX    11590088
dtype: int64

In [13]:
df.tail(20)

,DATE,TIME_M,EX,BID,BIDSIZ,ASK,ASKSIZ,QU_COND,QU_SEQNUM,NATBBO_IND,QU_CANCEL,QU_SOURCE,SYM_ROOT,SYM_SUFFIX
11590068,2023-05-10,19:59:41.456649861,K,171.27,3,174.11,1,R,84327836,0,NaN,N,AAPL,NaN
11590069,2023-05-10,19:59:45.447110853,Z,155.56,1,175.00,1,R,84327897,0,NaN,N,AAPL,NaN
11590070,2023-05-10,19:59:45.447119490,Z,155.56,1,175.00,1,R,84327898,0,NaN,N,AAPL,NaN
11590071,2023-05-10,19:59:45.941639792,Q,173.58,1,173.67,1,R,84327902,2,NaN,N,AAPL,NaN
11590072,2023-05-10,19:59:45.950813987,Z,155.56,1,175.00,1,R,84327904,0,NaN,N,AAPL,NaN
11590073,2023-05-10,19:59:45.959535717,K,171.27,3,174.11,1,R,84327909,0,NaN,N,AAPL,NaN
11590074,2023-05-10,19:59:45.961905952,K,171.27,3,174.11,1,R,84327910,0,NaN,N,AAPL,NaN
11590075,2023-05-10,19:59:45.968171223,Z,155.56,1,0.00,0,Y,84327911,0,NaN,N,AAPL,NaN
11590076,2023-05-10,19:59:45.975759585,Z,155.56,1,0.00,0,Y,84327912,0,NaN,N,AAPL,NaN
11590077,2023-05-10,19:59:45.986351652,K,171.27,3,174.11,1,R,84327913,0,NaN,N,AAPL,NaN
11590078,2023-05-10,19:59:48.829091152,K,171.27,3,173.64,2,R,84327925,2,NaN,N,AAPL,NaN
11590079,2023-05-10,19:59:48.830194579,Q,173.55,2,173.67,1,R,84327926,0,NaN,N,AAPL,NaN
11590080,2023-05-10,19:59:48.830678206,Z,155.56,1,0.00,0,Y,84327927,0,NaN,N,AAPL,NaN
11590081,2023-05-10,19:59:48.831741782,K,171.27,3,173.64,1,R,84327928,2,NaN,N,AAPL,NaN
11590082,2023-05-10,19:59:50.053106004,Z,155.56,1,0.00,0,Y,84327936,0,NaN,N,AAPL,NaN
11590083,2023-05-10,19:59:50.453822461,P,173.60,1,173.67,2,R,84327940,2,NaN,N,AAPL,NaN
11590084,2023-05-10,19:59:51.443939907,K,171.27,3,173.64,2,R,84327954,2,NaN,N,AAPL,NaN
11590085,2023-05-10,19:59:58.768274126,P,173.60,1,173.65,2,R,84328089,0,NaN,N,AAPL,NaN
11590086,2023-05-10,19:59:59.002624279,P,173.60,1,173.65,1,R,84328101,0,NaN,N,AAPL,NaN
11590087,2023-05-10,19:59:59.002669920,K,171.27,3,173.64,1,R,84328102,2,NaN,N,AAPL,NaN